export const AUTOMATION_PROCESS_MATRIX_ROWS = [
  {
    "layer": "📥 WARSTWA A: INPUT & RECEPTION",
    "module": "Input Control Center",
    "functionality": "Email Intake",
    "agent": "Email Intake Agent",
    "integrations": "Gmail/Outlook/SMTP",
    "actionType": "Reactive",
    "autonomyLevel": 3,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Klasyfikacja i routing automatyczny"
  },
  {
    "layer": "📥 WARSTWA A: INPUT & RECEPTION",
    "module": "Input Control Center",
    "functionality": "Form Intake",
    "agent": "Form Intake Agent",
    "integrations": "Formularze WWW/Landing pages",
    "actionType": "Reactive",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Lead capture i wzbogacanie"
  },
  {
    "layer": "📥 WARSTWA A: INPUT & RECEPTION",
    "module": "Input Control Center",
    "functionality": "Call Transcription",
    "agent": "Call Transcription Agent",
    "integrations": "VoIP/Call center",
    "actionType": "Reactive",
    "autonomyLevel": 3,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Transkrypcja i analiza rozmów"
  },
  {
    "layer": "📥 WARSTWA A: INPUT & RECEPTION",
    "module": "Input Control Center",
    "functionality": "Message Intake",
    "agent": "Message Intake Agent",
    "integrations": "WhatsApp/Messenger/Telegram",
    "actionType": "Reactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Obsługa komunikatorów"
  },
  {
    "layer": "📥 WARSTWA A: INPUT & RECEPTION",
    "module": "Input Control Center",
    "functionality": "Classification",
    "agent": "Classification Engine",
    "integrations": "NLP/ML models",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Auto-kategoryzacja zgłoszeń"
  },
  {
    "layer": "📥 WARSTWA A: INPUT & RECEPTION",
    "module": "Input Control Center",
    "functionality": "Deduplication",
    "agent": "Deduplication Agent",
    "integrations": "CRM/Database",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Usuwanie duplikatów"
  },
  {
    "layer": "📥 WARSTWA A: INPUT & RECEPTION",
    "module": "Input Control Center",
    "functionality": "Routing",
    "agent": "Routing Agent",
    "integrations": "Event Bus/Orchestrator",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Inteligentny routing spraw"
  },
  {
    "layer": "🔍 WARSTWA B: LEAD INTELLIGENCE",
    "module": "Lead Intelligence",
    "functionality": "Lead Research",
    "agent": "Lead Research Agent",
    "integrations": "LinkedIn/CEIDG/KRS/Web scraping",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Enrichment leadów"
  },
  {
    "layer": "🔍 WARSTWA B: LEAD INTELLIGENCE",
    "module": "Lead Intelligence",
    "functionality": "Scoring",
    "agent": "Scoring Agent",
    "integrations": "ML models/CRM history",
    "actionType": "Predictive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Lead scoring 0-100"
  },
  {
    "layer": "🔍 WARSTWA B: LEAD INTELLIGENCE",
    "module": "Lead Intelligence",
    "functionality": "ICP Match",
    "agent": "ICP Match Agent",
    "integrations": "Customer profiling/Segmentation",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Dopasowanie do ideal customer profile"
  },
  {
    "layer": "🔍 WARSTWA B: LEAD INTELLIGENCE",
    "module": "Lead Intelligence",
    "functionality": "Risk Assessment",
    "agent": "Risk Assessment Agent",
    "integrations": "Credit check/Payment history",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Tak",
    "autonomousDecision": "Ocena ryzyka kredytowego >50k PLN"
  },
  {
    "layer": "🔍 WARSTWA B: LEAD INTELLIGENCE",
    "module": "Lead Intelligence",
    "functionality": "Assignment",
    "agent": "Assignment Agent",
    "integrations": "CRM/Calendar/Workload analysis",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Auto-przypisanie do opiekuna"
  },
  {
    "layer": "🔍 WARSTWA B: LEAD INTELLIGENCE",
    "module": "Lead Intelligence",
    "functionality": "Intent Detection",
    "agent": "Intent Detection Agent",
    "integrations": "NLP/Behavioral analysis",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Wykrywanie intencji zakupowej"
  },
  {
    "layer": "🔍 WARSTWA B: LEAD INTELLIGENCE",
    "module": "Lead Intelligence",
    "functionality": "LTV Prediction",
    "agent": "LTV Prediction Agent",
    "integrations": "ML models/Historical data",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🔵 Planned",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Prognoza wartości życiowej klienta"
  },
  {
    "layer": "💼 WARSTWA C: SALES COMMAND CENTER",
    "module": "Sales Command",
    "functionality": "Offer Builder",
    "agent": "Offer Builder Agent",
    "integrations": "CPQ/Product catalog/Pricing engine",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Oferty do 50k PLN bez akceptacji"
  },
  {
    "layer": "💼 WARSTWA C: SALES COMMAND CENTER",
    "module": "Sales Command",
    "functionality": "Follow-Up",
    "agent": "Follow-Up Agent",
    "integrations": "Email/CRM/Calendar",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Automatyczne follow-upy (3 próby)"
  },
  {
    "layer": "💼 WARSTWA C: SALES COMMAND CENTER",
    "module": "Sales Command",
    "functionality": "Negotiation Support",
    "agent": "Negotiation Support Agent",
    "integrations": "Historical deals/Pricing strategy",
    "actionType": "Proactive",
    "autonomyLevel": 3,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Tak",
    "autonomousDecision": "Sugestie w negocjacjach"
  },
  {
    "layer": "💼 WARSTWA C: SALES COMMAND CENTER",
    "module": "Sales Command",
    "functionality": "Deal Health",
    "agent": "Deal Health Agent",
    "integrations": "Pipeline analysis/ML models",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Wykrywanie zagrożonych dealów"
  },
  {
    "layer": "💼 WARSTWA C: SALES COMMAND CENTER",
    "module": "Sales Command",
    "functionality": "Pricing",
    "agent": "Pricing Agent",
    "integrations": "Competitor data/Margin rules",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Rabaty do 7% autonomicznie"
  },
  {
    "layer": "💼 WARSTWA C: SALES COMMAND CENTER",
    "module": "Sales Command",
    "functionality": "Upsell/Cross-Sell",
    "agent": "Upsell/Cross-Sell Agent",
    "integrations": "Purchase patterns/Product affinity",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Rekomendacje produktów"
  },
  {
    "layer": "💼 WARSTWA C: SALES COMMAND CENTER",
    "module": "Sales Command",
    "functionality": "Contract Generation",
    "agent": "Contract Generation Agent",
    "integrations": "Templates/Legal rules/DocuSign",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Tak",
    "autonomousDecision": "Umowy standardowe bez prawnika"
  },
  {
    "layer": "📦 WARSTWA D: PRODUCT & CATALOG",
    "module": "Product Brain",
    "functionality": "Product Normalization",
    "agent": "Product Normalization Agent",
    "integrations": "PIM/ERP/Marketplace feeds",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Ujednolicanie katalogów"
  },
  {
    "layer": "📦 WARSTWA D: PRODUCT & CATALOG",
    "module": "Product Brain",
    "functionality": "Content Generation",
    "agent": "Content Generation Agent",
    "integrations": "GPT-4/Product data/SEO rules",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Opisy produktów"
  },
  {
    "layer": "📦 WARSTWA D: PRODUCT & CATALOG",
    "module": "Product Brain",
    "functionality": "Attribute Mapping",
    "agent": "Attribute Mapping Agent",
    "integrations": "ML/Product taxonomy",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Mapowanie cech produktów"
  },
  {
    "layer": "📦 WARSTWA D: PRODUCT & CATALOG",
    "module": "Product Brain",
    "functionality": "Category",
    "agent": "Category Agent",
    "integrations": "Classification models",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🟢 Live",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Auto-kategoryzacja"
  },
  {
    "layer": "📦 WARSTWA D: PRODUCT & CATALOG",
    "module": "Product Brain",
    "functionality": "Translation",
    "agent": "Translation Agent",
    "integrations": "DeepL/GPT-4",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Średni",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 7,
    "guardrails": "Nie",
    "autonomousDecision": "Tłumaczenia katalogów"
  },
  {
    "layer": "📦 WARSTWA D: PRODUCT & CATALOG",
    "module": "Product Brain",
    "functionality": "Compliance",
    "agent": "Compliance Agent",
    "integrations": "Legal rules/Regulations",
    "actionType": "Proactive",
    "autonomyLevel": 3,
    "businessImpact": "Wysoki",
    "implementationStatus": "🔵 Planned",
    "roiScore": 8,
    "guardrails": "Tak",
    "autonomousDecision": "Zgodność z regulacjami"
  },
  {
    "layer": "📦 WARSTWA D: PRODUCT & CATALOG",
    "module": "Product Brain",
    "functionality": "Image Enhancement",
    "agent": "Image Enhancement Agent",
    "integrations": "Computer Vision/DAM",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🔵 Planned",
    "roiScore": 7,
    "guardrails": "Nie",
    "autonomousDecision": "Optymalizacja zdjęć"
  },
  {
    "layer": "💰 WARSTWA E: PRICING & MARGIN",
    "module": "Pricing Engine",
    "functionality": "Competitor Monitoring",
    "agent": "Competitor Monitoring Agent",
    "integrations": "Web scraping/Price aggregators",
    "actionType": "Proactive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Monitoring 24/7"
  },
  {
    "layer": "💰 WARSTWA E: PRICING & MARGIN",
    "module": "Pricing Engine",
    "functionality": "Margin Protection",
    "agent": "Margin Protection Agent",
    "integrations": "ERP/Cost data/Rules engine",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Ochrona minimalnej marży 15%"
  },
  {
    "layer": "💰 WARSTWA E: PRICING & MARGIN",
    "module": "Pricing Engine",
    "functionality": "Dynamic Pricing",
    "agent": "Dynamic Pricing Agent",
    "integrations": "ML models/Demand elasticity",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Zmiany cen w zakresie ±10%"
  },
  {
    "layer": "💰 WARSTWA E: PRICING & MARGIN",
    "module": "Pricing Engine",
    "functionality": "Promotion",
    "agent": "Promotion Agent",
    "integrations": "Sales data/Inventory levels",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Promocje do 20% rabatu"
  },
  {
    "layer": "💰 WARSTWA E: PRICING & MARGIN",
    "module": "Pricing Engine",
    "functionality": "Profitability",
    "agent": "Profitability Agent",
    "integrations": "Full cost analysis/Margin tracking",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Analiza rentowności"
  },
  {
    "layer": "💰 WARSTWA E: PRICING & MARGIN",
    "module": "Pricing Engine",
    "functionality": "Market Positioning",
    "agent": "Market Positioning Agent",
    "integrations": "Competitive intelligence",
    "actionType": "Predictive",
    "autonomyLevel": 3,
    "businessImpact": "Wysoki",
    "implementationStatus": "🔵 Planned",
    "roiScore": 8,
    "guardrails": "Tak",
    "autonomousDecision": "Strategia pozycjonowania cenowego"
  },
  {
    "layer": "🛒 WARSTWA F: PROCUREMENT",
    "module": "Procurement",
    "functionality": "Replenishment",
    "agent": "Replenishment Agent",
    "integrations": "Demand forecast/Stock levels",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Zamówienia do 100k PLN"
  },
  {
    "layer": "🛒 WARSTWA F: PROCUREMENT",
    "module": "Procurement",
    "functionality": "Supplier Comparison",
    "agent": "Supplier Comparison Agent",
    "integrations": "Price/Quality/Delivery time",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Ranking dostawców"
  },
  {
    "layer": "🛒 WARSTWA F: PROCUREMENT",
    "module": "Procurement",
    "functionality": "Purchase Order",
    "agent": "Purchase Order Agent",
    "integrations": "ERP/Supplier APIs/Email",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "PO do zatwierdzonych dostawców"
  },
  {
    "layer": "🛒 WARSTWA F: PROCUREMENT",
    "module": "Procurement",
    "functionality": "Delay Prediction",
    "agent": "Delay Prediction Agent",
    "integrations": "ML/Historical data/External signals",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Prognoza opóźnień dostaw"
  },
  {
    "layer": "🛒 WARSTWA F: PROCUREMENT",
    "module": "Procurement",
    "functionality": "Supplier Risk",
    "agent": "Supplier Risk Agent",
    "integrations": "Financial data/News/Performance",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Alert przy ryzyku >70%"
  },
  {
    "layer": "🛒 WARSTWA F: PROCUREMENT",
    "module": "Procurement",
    "functionality": "Contract Negotiation",
    "agent": "Contract Negotiation Agent",
    "integrations": "Historical terms/Market data",
    "actionType": "Proactive",
    "autonomyLevel": 3,
    "businessImpact": "Średni",
    "implementationStatus": "🔵 Planned",
    "roiScore": 7,
    "guardrails": "Tak",
    "autonomousDecision": "Sugestie warunków umów"
  },
  {
    "layer": "🛒 WARSTWA F: PROCUREMENT",
    "module": "Procurement",
    "functionality": "Quality Control",
    "agent": "Quality Control Agent",
    "integrations": "Returns/Complaints/Ratings",
    "actionType": "Reactive",
    "autonomyLevel": 3,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Monitoring jakości dostaw"
  },
  {
    "layer": "🏭 WARSTWA G: WAREHOUSE",
    "module": "Warehouse",
    "functionality": "Stock Health",
    "agent": "Stock Health Agent",
    "integrations": "WMS/Real-time inventory",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Monitoring stanów 24/7"
  },
  {
    "layer": "🏭 WARSTWA G: WAREHOUSE",
    "module": "Warehouse",
    "functionality": "Overstock/Understock",
    "agent": "Overstock/Understock Agent",
    "integrations": "Demand forecast/ABC analysis",
    "actionType": "Predictive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Alerty i rekomendacje"
  },
  {
    "layer": "🏭 WARSTWA G: WAREHOUSE",
    "module": "Warehouse",
    "functionality": "Picking Optimization",
    "agent": "Picking Optimization Agent",
    "integrations": "WMS/Route optimization",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Optymalizacja kompletacji"
  },
  {
    "layer": "🏭 WARSTWA G: WAREHOUSE",
    "module": "Warehouse",
    "functionality": "Inventory Audit",
    "agent": "Inventory Audit Agent",
    "integrations": "IoT/RFID/Cycle counting",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Ciągła inwentaryzacja"
  },
  {
    "layer": "🏭 WARSTWA G: WAREHOUSE",
    "module": "Warehouse",
    "functionality": "Shrinkage Detection",
    "agent": "Shrinkage Detection Agent",
    "integrations": "Anomaly detection/Pattern analysis",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🔵 Planned",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Wykrywanie braków >5%"
  },
  {
    "layer": "🏭 WARSTWA G: WAREHOUSE",
    "module": "Warehouse",
    "functionality": "Location Optimization",
    "agent": "Location Optimization Agent",
    "integrations": "WMS/Movement patterns",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🔵 Planned",
    "roiScore": 7,
    "guardrails": "Nie",
    "autonomousDecision": "Optymalizacja lokalizacji"
  },
  {
    "layer": "🏭 WARSTWA G: WAREHOUSE",
    "module": "Warehouse",
    "functionality": "Returns Processing",
    "agent": "Returns Processing Agent",
    "integrations": "WMS/Quality check/Disposition",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Automatyczna dyspozycja zwrotów"
  },
  {
    "layer": "📋 WARSTWA H: ORDER ORCHESTRATION",
    "module": "Order Orchestration",
    "functionality": "Order Validation",
    "agent": "Order Validation Agent",
    "integrations": "Business rules/Fraud detection",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Blokada podejrzanych >20k PLN"
  },
  {
    "layer": "📋 WARSTWA H: ORDER ORCHESTRATION",
    "module": "Order Orchestration",
    "functionality": "Allocation",
    "agent": "Allocation Agent",
    "integrations": "Multi-warehouse/Availability",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Inteligentna alokacja"
  },
  {
    "layer": "📋 WARSTWA H: ORDER ORCHESTRATION",
    "module": "Order Orchestration",
    "functionality": "Fulfillment",
    "agent": "Fulfillment Agent",
    "integrations": "WMS/Logistics/Picking",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Orkiestracja realizacji"
  },
  {
    "layer": "📋 WARSTWA H: ORDER ORCHESTRATION",
    "module": "Order Orchestration",
    "functionality": "Exception Handling",
    "agent": "Exception Handling Agent",
    "integrations": "Rules engine/Escalation",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Eskalacja wyjątków >10k PLN"
  },
  {
    "layer": "📋 WARSTWA H: ORDER ORCHESTRATION",
    "module": "Order Orchestration",
    "functionality": "Customer Status",
    "agent": "Customer Status Agent",
    "integrations": "Email/SMS/Portal updates",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Automatyczne statusy"
  },
  {
    "layer": "📋 WARSTWA H: ORDER ORCHESTRATION",
    "module": "Order Orchestration",
    "functionality": "Split Order",
    "agent": "Split Order Agent",
    "integrations": "Availability/Customer preference",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 8,
    "guardrails": "Tak",
    "autonomousDecision": "Podział zamówień >5 pozycji"
  },
  {
    "layer": "📋 WARSTWA H: ORDER ORCHESTRATION",
    "module": "Order Orchestration",
    "functionality": "Backorder Management",
    "agent": "Backorder Management Agent",
    "integrations": "ETA/Customer communication",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Zarządzanie backorderami"
  },
  {
    "layer": "🚚 WARSTWA I: LOGISTICS",
    "module": "Logistics",
    "functionality": "Carrier Selection",
    "agent": "Carrier Selection Agent",
    "integrations": "Cost/Speed/Reliability/SLA",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Wybór kuriera według reguł"
  },
  {
    "layer": "🚚 WARSTWA I: LOGISTICS",
    "module": "Logistics",
    "functionality": "Delay Monitoring",
    "agent": "Delay Monitoring Agent",
    "integrations": "Tracking APIs/ML prediction",
    "actionType": "Predictive",
    "autonomyLevel": 5,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Real-time monitoring"
  },
  {
    "layer": "🚚 WARSTWA I: LOGISTICS",
    "module": "Logistics",
    "functionality": "Freight Cost",
    "agent": "Freight Cost Agent",
    "integrations": "Rate shopping/Contract rates",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Optymalizacja kosztów"
  },
  {
    "layer": "🚚 WARSTWA I: LOGISTICS",
    "module": "Logistics",
    "functionality": "Delivery Issue",
    "agent": "Delivery Issue Agent",
    "integrations": "Exception handling/Communication",
    "actionType": "Reactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Obsługa problemów"
  },
  {
    "layer": "🚚 WARSTWA I: LOGISTICS",
    "module": "Logistics",
    "functionality": "Route Optimization",
    "agent": "Route Optimization Agent",
    "integrations": "GPS/Traffic/Multi-drop",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🔵 Planned",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Optymalizacja tras"
  },
  {
    "layer": "🚚 WARSTWA I: LOGISTICS",
    "module": "Logistics",
    "functionality": "Returns Logistics",
    "agent": "Returns Logistics Agent",
    "integrations": "Reverse logistics/Labels",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Obsługa zwrotów"
  },
  {
    "layer": "🚚 WARSTWA I: LOGISTICS",
    "module": "Logistics",
    "functionality": "Proof of Delivery",
    "agent": "Proof of Delivery Agent",
    "integrations": "POD capture/Validation",
    "actionType": "Reactive",
    "autonomyLevel": 3,
    "businessImpact": "Średni",
    "implementationStatus": "🟢 Live",
    "roiScore": 7,
    "guardrails": "Nie",
    "autonomousDecision": "Potwierdzenia dostaw"
  },
  {
    "layer": "💵 WARSTWA J: FINANCE",
    "module": "Finance",
    "functionality": "Receivables",
    "agent": "Receivables Agent",
    "integrations": "Invoices/Payment tracking/Reminders",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Windykacja miękka 3 przypomnienia"
  },
  {
    "layer": "💵 WARSTWA J: FINANCE",
    "module": "Finance",
    "functionality": "Payables",
    "agent": "Payables Agent",
    "integrations": "Invoice matching/Payment scheduling",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Płatności do 50k PLN"
  },
  {
    "layer": "💵 WARSTWA J: FINANCE",
    "module": "Finance",
    "functionality": "Cashflow Forecast",
    "agent": "Cashflow Forecast Agent",
    "integrations": "ML models/Historical patterns",
    "actionType": "Predictive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Prognoza 90 dni"
  },
  {
    "layer": "💵 WARSTWA J: FINANCE",
    "module": "Finance",
    "functionality": "Margin Analytics",
    "agent": "Margin Analytics Agent",
    "integrations": "Full P&L/Product/Customer/Channel",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Real-time margin tracking"
  },
  {
    "layer": "💵 WARSTWA J: FINANCE",
    "module": "Finance",
    "functionality": "Fraud Detection",
    "agent": "Fraud Detection Agent",
    "integrations": "Anomaly detection/Pattern analysis",
    "actionType": "Predictive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Blokada podejrzanych transakcji"
  },
  {
    "layer": "💵 WARSTWA J: FINANCE",
    "module": "Finance",
    "functionality": "Credit Limit",
    "agent": "Credit Limit Agent",
    "integrations": "Credit scoring/Payment history",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Limity do 100k PLN"
  },
  {
    "layer": "💵 WARSTWA J: FINANCE",
    "module": "Finance",
    "functionality": "Reconciliation",
    "agent": "Reconciliation Agent",
    "integrations": "Bank/ERP/Accounting matching",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Auto-uzgodnienia"
  },
  {
    "layer": "👥 WARSTWA K: CUSTOMER SUCCESS",
    "module": "Customer Success",
    "functionality": "Support Triage",
    "agent": "Support Triage Agent",
    "integrations": "NLP/Urgency detection/Routing",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Priorytetyzacja zgłoszeń"
  },
  {
    "layer": "👥 WARSTWA K: CUSTOMER SUCCESS",
    "module": "Customer Success",
    "functionality": "Customer Emotion",
    "agent": "Customer Emotion Agent",
    "integrations": "Sentiment analysis/Tone detection",
    "actionType": "Reactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Eskalacja negatywnych"
  },
  {
    "layer": "👥 WARSTWA K: CUSTOMER SUCCESS",
    "module": "Customer Success",
    "functionality": "Churn Risk",
    "agent": "Churn Risk Agent",
    "integrations": "ML models/Behavioral signals",
    "actionType": "Predictive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Alert przy ryzyku >60%"
  },
  {
    "layer": "👥 WARSTWA K: CUSTOMER SUCCESS",
    "module": "Customer Success",
    "functionality": "Return/Complaint",
    "agent": "Return/Complaint Agent",
    "integrations": "RMA/Resolution workflows",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Zwroty do 5k PLN bez akceptacji"
  },
  {
    "layer": "👥 WARSTWA K: CUSTOMER SUCCESS",
    "module": "Customer Success",
    "functionality": "Resolution",
    "agent": "Resolution Agent",
    "integrations": "Knowledge base/Auto-responses",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Odpowiedzi na FAQ"
  },
  {
    "layer": "👥 WARSTWA K: CUSTOMER SUCCESS",
    "module": "Customer Success",
    "functionality": "Satisfaction",
    "agent": "Satisfaction Agent",
    "integrations": "NPS/CSAT/Surveys",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🟢 Live",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Automatyczne ankiety"
  },
  {
    "layer": "👥 WARSTWA K: CUSTOMER SUCCESS",
    "module": "Customer Success",
    "functionality": "Retention",
    "agent": "Retention Agent",
    "integrations": "Offers/Loyalty programs",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Oferty retencyjne do 10% rabatu"
  },
  {
    "layer": "📣 WARSTWA L: MARKETING",
    "module": "Marketing",
    "functionality": "Campaign",
    "agent": "Campaign Agent",
    "integrations": "Audience/Creative/Budget/Schedule",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Kampanie do 10k PLN/mies"
  },
  {
    "layer": "📣 WARSTWA L: MARKETING",
    "module": "Marketing",
    "functionality": "Content",
    "agent": "Content Agent",
    "integrations": "GPT-4/Brand voice/SEO",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Content production"
  },
  {
    "layer": "📣 WARSTWA L: MARKETING",
    "module": "Marketing",
    "functionality": "Audience",
    "agent": "Audience Agent",
    "integrations": "Segmentation/Lookalike/Retargeting",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Inteligentne segmenty"
  },
  {
    "layer": "📣 WARSTWA L: MARKETING",
    "module": "Marketing",
    "functionality": "Performance",
    "agent": "Performance Agent",
    "integrations": "ROI/ROAS/Attribution/Optimization",
    "actionType": "Predictive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Auto-optymalizacja budżetu"
  },
  {
    "layer": "📣 WARSTWA L: MARKETING",
    "module": "Marketing",
    "functionality": "SEO",
    "agent": "SEO Agent",
    "integrations": "Keywords/Content/Technical/Backlinks",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "SEO recommendations"
  },
  {
    "layer": "📣 WARSTWA L: MARKETING",
    "module": "Marketing",
    "functionality": "Marketplace Content",
    "agent": "Marketplace Content Agent",
    "integrations": "Product titles/Bullets/A+ content",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Optymalizacja listingów"
  },
  {
    "layer": "📣 WARSTWA L: MARKETING",
    "module": "Marketing",
    "functionality": "Email Automation",
    "agent": "Email Automation Agent",
    "integrations": "Flows/Personalization/Timing",
    "actionType": "Autonomous",
    "autonomyLevel": 5,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟢 Live",
    "roiScore": 9,
    "guardrails": "Nie",
    "autonomousDecision": "Automated email journeys"
  },
  {
    "layer": "👨‍💼 WARSTWA M: HR & INTERNAL",
    "module": "HR",
    "functionality": "Onboarding",
    "agent": "Onboarding Agent",
    "integrations": "Training/Documentation/Tasks",
    "actionType": "Autonomous",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Automatyczny onboarding"
  },
  {
    "layer": "👨‍💼 WARSTWA M: HR & INTERNAL",
    "module": "HR",
    "functionality": "SOP Coach",
    "agent": "SOP Coach Agent",
    "integrations": "Procedures/Best practices/Q&A",
    "actionType": "Reactive",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Internal knowledge assistant"
  },
  {
    "layer": "👨‍💼 WARSTWA M: HR & INTERNAL",
    "module": "HR",
    "functionality": "Workload",
    "agent": "Workload Agent",
    "integrations": "Task distribution/Capacity planning",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🔵 Planned",
    "roiScore": 8,
    "guardrails": "Nie",
    "autonomousDecision": "Równoważenie obciążenia"
  },
  {
    "layer": "👨‍💼 WARSTWA M: HR & INTERNAL",
    "module": "HR",
    "functionality": "Internal Helpdesk",
    "agent": "Internal Helpdesk Agent",
    "integrations": "IT/HR/Admin support",
    "actionType": "Reactive",
    "autonomyLevel": 4,
    "businessImpact": "Średni",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 7,
    "guardrails": "Nie",
    "autonomousDecision": "L1 support automation"
  },
  {
    "layer": "👨‍💼 WARSTWA M: HR & INTERNAL",
    "module": "HR",
    "functionality": "Performance Tracking",
    "agent": "Performance Tracking Agent",
    "integrations": "KPIs/Goals/Feedback",
    "actionType": "Proactive",
    "autonomyLevel": 3,
    "businessImpact": "Średni",
    "implementationStatus": "🔵 Planned",
    "roiScore": 7,
    "guardrails": "Tak",
    "autonomousDecision": "Performance insights"
  },
  {
    "layer": "👨‍💼 WARSTWA M: HR & INTERNAL",
    "module": "HR",
    "functionality": "Skills Gap",
    "agent": "Skills Gap Agent",
    "integrations": "Training needs/Development plans",
    "actionType": "Predictive",
    "autonomyLevel": 3,
    "businessImpact": "Średni",
    "implementationStatus": "🟣 Concept",
    "roiScore": 7,
    "guardrails": "Tak",
    "autonomousDecision": "Rekomendacje szkoleń"
  },
  {
    "layer": "🏢 WARSTWA N: EXECUTIVE",
    "module": "Executive",
    "functionality": "CEO Briefing",
    "agent": "CEO Briefing Agent",
    "integrations": "Daily summary/Priorities/Alerts",
    "actionType": "Proactive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Codzienny brief 7:00"
  },
  {
    "layer": "🏢 WARSTWA N: EXECUTIVE",
    "module": "Executive",
    "functionality": "KPI",
    "agent": "KPI Agent",
    "integrations": "Real-time metrics/Dashboards",
    "actionType": "Reactive",
    "autonomyLevel": 5,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟢 Live",
    "roiScore": 10,
    "guardrails": "Nie",
    "autonomousDecision": "Live KPI tracking"
  },
  {
    "layer": "🏢 WARSTWA N: EXECUTIVE",
    "module": "Executive",
    "functionality": "Strategic Risk",
    "agent": "Strategic Risk Agent",
    "integrations": "Market/Financial/Operational risks",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Krytyczny",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 10,
    "guardrails": "Tak",
    "autonomousDecision": "Critical risk alerts"
  },
  {
    "layer": "🏢 WARSTWA N: EXECUTIVE",
    "module": "Executive",
    "functionality": "Opportunity Discovery",
    "agent": "Opportunity Discovery Agent",
    "integrations": "Market gaps/Trends/New segments",
    "actionType": "Predictive",
    "autonomyLevel": 4,
    "businessImpact": "Wysoki",
    "implementationStatus": "🟡 Pilot",
    "roiScore": 9,
    "guardrails": "Tak",
    "autonomousDecision": "Strategic opportunities"
  },
  {
    "layer": "🏢 WARSTWA N: EXECUTIVE",
    "module": "Executive",
    "functionality": "Board Report",
    "agent": "Board Report Agent",
    "integrations": "Monthly/Quarterly reports",
    "actionType": "Proactive",
    "autonomyLevel": 4,
    "businessImpact": "",
    "implementationStatus": "",
    "roiScore": null,
    "guardrails": "",
    "autonomousDecision": ""
  }
] as const;
