import type { AppLocale } from "@mulagroup/content-models";

export type DataFlowDomain = {
  id: string;
  integrations: string[];
  side: "left" | "right";
  title: string;
  tone: string;
};

export type DataFlowArchitectureModel = {
  copy: {
    countLabel: string;
    ctaLabel: string;
    ctaTitle: string;
    description: string;
    eyebrow: string;
    supportLine: string;
    title: string;
  };
  coreLabel: string;
  domains: DataFlowDomain[];
};

const COPY = {
  en: {
    countLabel: "25 integrations",
    ctaLabel: "Book a strategy conversation",
    ctaTitle: "Want a mapped data-flow architecture for your company?",
    description:
      "A Mula Group architecture can connect acquisition, CRM, customer service, operations, logistics, finance, ERP, AI and reporting into one live company data spine.",
    eyebrow: "Company data flow architecture",
    supportLine: "One data core. Ten connected operating domains. Hundreds of synchronized signals.",
    title: "How Data Moves Through the Connected Business System",
  },
  pl: {
    countLabel: "25 integracji",
    ctaLabel: "Umów rozmowę strategiczną",
    ctaTitle: "Chcesz zobaczyć mapę przepływu danych dla swojej firmy?",
    description:
      "Architektura Mula Group może połączyć marketing, CRM, obsługę klienta, operacje, logistykę, finanse, ERP, AI i raportowanie w jeden żywy rdzeń danych firmy.",
    eyebrow: "Architektura przepływu danych firmy",
    supportLine: "Jeden rdzeń danych. Dziesięć połączonych domen operacyjnych. Setki zsynchronizowanych sygnałów.",
    title: "Jak Dane Przepływają Przez Połączony System Firmy",
  },
} as const;

const TITLES = {
  en: {
    ai: "AI & Automation",
    commerce: "Commerce & Orders",
    erp: "ERP & Inventory",
    finance: "Finance & Accounting",
    logistics: "Logistics & Fulfillment",
    marketing: "Marketing & Acquisition",
    operations: "Operations & Workflow",
    reporting: "Reporting & Management",
    sales: "Sales & CRM",
    support: "Customer Support & Communication",
  },
  pl: {
    ai: "AI i automatyzacje",
    commerce: "Commerce i zamówienia",
    erp: "ERP i magazyn",
    finance: "Finanse i księgowość",
    logistics: "Logistyka i realizacja",
    marketing: "Marketing i pozyskiwanie",
    operations: "Operacje i workflow",
    reporting: "Raportowanie i zarządzanie",
    sales: "Sprzedaż i CRM",
    support: "Obsługa klienta i komunikacja",
  },
} as const;

const DOMAIN_DEFINITIONS = [
  {
    id: "reporting",
    integrations: [
      "Owner dashboard",
      "Sales dashboard",
      "Marketing dashboard",
      "Operations dashboard",
      "Logistics dashboard",
      "Finance dashboard",
      "ERP dashboard",
      "Client growth dashboard",
      "Retainer dashboard",
      "Weekly operating summary",
      "Monthly review summary",
      "Quarterly strategy input",
      "Pillar performance dashboard",
      "CTA performance report",
      "Funnel conversion report",
      "Lead quality report",
      "Source attribution report",
      "Team workload report",
      "SLA / support report",
      "Alert center",
      "Executive KPI board",
      "Forecasting support",
      "Expansion opportunity report",
      "Risk / anomaly report",
      "Management decision summary",
    ],
    side: "left",
    tone: "#ff7157",
  },
  {
    id: "finance",
    integrations: [
      "Fakturowanie",
      "Korekty / credit notes",
      "Payment gateway reconciliation",
      "Bank sync",
      "Accounts receivable",
      "Accounts payable",
      "Cash flow snapshot",
      "Margin calculation",
      "Cost center mapping",
      "Tax classification",
      "VAT handling",
      "Bookkeeping export",
      "Accounting software sync",
      "Billing reminders",
      "Debt collection workflow",
      "Split payment support",
      "Expense approval",
      "Expense OCR import",
      "Contract billing logic",
      "Retainer invoicing",
      "Subscription billing",
      "Financial close checklist",
      "Profitability by client",
      "Profitability by project",
      "Finance dashboard feed",
    ],
    side: "left",
    tone: "#f3ab44",
  },
  {
    id: "erp",
    integrations: [
      "ERP master sync",
      "SKU master data",
      "Product master data",
      "Stock levels",
      "Multi-warehouse stock",
      "Purchase orders",
      "Supplier master",
      "Supplier sync",
      "Goods receipt / PZ",
      "Goods issue / WZ",
      "Inventory movement",
      "Serial number tracking",
      "Batch / lot tracking",
      "Reorder rules",
      "Safety stock alerts",
      "Demand planning input",
      "MRP support",
      "Production order sync",
      "BOM / recipe support",
      "Reservation logic",
      "Warehouse location logic",
      "Transfer between warehouses",
      "Inventory audit",
      "Stock discrepancy alerts",
      "ERP reporting feed",
    ],
    side: "left",
    tone: "#ddc746",
  },
  {
    id: "commerce",
    integrations: [
      "Sklep internetowy",
      "B2B ordering portal",
      "Allegro sync",
      "Amazon sync",
      "eBay sync",
      "Product catalog sync",
      "Product variants",
      "Pricing rules",
      "Promotions engine",
      "Coupon engine",
      "Cart recovery",
      "Order import",
      "Order status sync",
      "Payment status sync",
      "Invoice trigger from order",
      "Subscription order support",
      "Quote-to-order flow",
      "Sales channel mapping",
      "Customer order history",
      "Product recommendation engine",
      "Wholesale pricing",
      "Dealer ordering support",
      "Marketplace stock sync",
      "Marketplace message sync",
      "Checkout event tracking",
    ],
    side: "left",
    tone: "#9edc4b",
  },
  {
    id: "logistics",
    integrations: [
      "Kurier A integration",
      "Kurier B integration",
      "Kurier C integration",
      "Label generation",
      "Shipment booking",
      "Tracking sync",
      "Dispatch confirmation",
      "Pickup point mapping",
      "Warehouse picking list",
      "Packing workflow",
      "Shipping cost calculator",
      "Multi-carrier routing",
      "Delivery ETA sync",
      "Shipment exception alerts",
      "Return labels",
      "Reverse logistics flow",
      "Claims / damage reporting",
      "Delivery proof capture",
      "Driver / carrier notes",
      "Pallet / bulk shipment support",
      "International shipping docs",
      "Customs document support",
      "Fulfillment center sync",
      "Shipping KPI feed",
      "Last-mile status dashboard",
    ],
    side: "left",
    tone: "#57d06d",
  },
  {
    id: "marketing",
    integrations: [
      "Strona WWW",
      "Landing pages",
      "Formularze leadowe",
      "Popupy i lead magnets",
      "Newsletter signup",
      "Consent / cookie manager",
      "Google Analytics",
      "Google Tag Manager",
      "Meta Pixel",
      "LinkedIn Insight Tag",
      "TikTok Pixel",
      "Google Ads lead sync",
      "Meta Lead Ads sync",
      "LinkedIn Lead Gen sync",
      "SEO monitoring",
      "Blog / content publishing",
      "UTM tracking",
      "Call tracking",
      "Live chat",
      "Chatbot pre-qualification",
      "Social media inbox capture",
      "Webinar registration",
      "Event registration",
      "Campaign attribution",
      "Source / medium enrichment",
    ],
    side: "right",
    tone: "#6f74ff",
  },
  {
    id: "sales",
    integrations: [
      "CRM contacts",
      "CRM companies",
      "CRM deals / pipeline",
      "Lead scoring",
      "AI triage leadów",
      "Lead deduplication",
      "Meeting scheduler",
      "Calendar sync",
      "Email sync",
      "VoIP / call logging",
      "Sales notes capture",
      "Proposal generator",
      "Offer approval flow",
      "Quote status tracking",
      "E-signature",
      "Follow-up automation",
      "Reminder engine",
      "Task assignment",
      "Owner routing",
      "Multi-pillar lead tagging",
      "Discovery intake",
      "Opportunity stage changes",
      "Lost reason tracking",
      "Reactivation logic",
      "Retainer-fit flag",
    ],
    side: "right",
    tone: "#a85dff",
  },
  {
    id: "support",
    integrations: [
      "Shared inbox",
      "Ticketing system",
      "SLA monitoring",
      "Complaint intake",
      "Returns support",
      "Customer chat history",
      "Email templates",
      "SMS notifications",
      "WhatsApp / messenger bridge",
      "Call center notes",
      "Customer identity merge",
      "Escalation logic",
      "Service appointment booking",
      "Callback requests",
      "FAQ knowledge base",
      "AI support summary",
      "Support categorization",
      "Customer satisfaction survey",
      "NPS survey",
      "Review request automation",
      "Case status notifications",
      "Internal support handoff",
      "VIP client tagging",
      "Priority queue rules",
      "Customer timeline view",
    ],
    side: "right",
    tone: "#3eb8ff",
  },
  {
    id: "operations",
    integrations: [
      "Task routing",
      "Internal project board",
      "Approval workflows",
      "Document circulation",
      "Service stage flow",
      "Operational checklist engine",
      "SOP trigger automation",
      "Team assignment rules",
      "Deadline reminders",
      "Escalation alerts",
      "Multi-step delivery workflow",
      "Internal request forms",
      "Procurement request flow",
      "HR/ops task handoff",
      "Quality control checkpoints",
      "Field service scheduling",
      "Installation workflow",
      "Maintenance workflow",
      "Onboarding workflow",
      "Offboarding workflow",
      "Internal audit trail",
      "Asset handover logic",
      "Signature / acceptance capture",
      "Workflow bottleneck alerts",
      "Operating status dashboard feed",
    ],
    side: "right",
    tone: "#f05aba",
  },
  {
    id: "ai",
    integrations: [
      "AI lead summary",
      "AI routing recommendation",
      "AI fit scoring suggestion",
      "AI urgency signal",
      "AI ecosystem potential signal",
      "AI meeting summary",
      "AI email draft support",
      "AI proposal draft support",
      "AI document extraction",
      "AI classification of inquiries",
      "AI support ticket summarization",
      "AI anomaly detection",
      "AI weekly summary draft",
      "AI monthly summary draft",
      "Workflow trigger engine",
      "Webhook orchestration",
      "No-code automation layer",
      "Data sync automations",
      "Notification automations",
      "Internal alert automations",
      "Approval reminder automations",
      "Follow-up due alerts",
      "AI knowledge retrieval",
      "AI decision support cards",
      "Automation health monitor",
    ],
    side: "right",
    tone: "#ff4f8f",
  },
] as const;

export function getDataFlowArchitectureModel(locale: AppLocale): DataFlowArchitectureModel {
  return {
    copy: COPY[locale],
    coreLabel: locale === "pl" ? "Rdzeń danych firmy" : "Company Data Core",
    domains: DOMAIN_DEFINITIONS.map((domain) => ({
      id: domain.id,
      integrations: [...domain.integrations],
      side: domain.side,
      title: TITLES[locale][domain.id],
      tone: domain.tone,
    })),
  };
}
